### ISSUE TITLE
Add Compatibility with Medic

### ISSUE THREAD

**Issue by sinsa92** [ZacharyHinds/ttt2-role-executioner#11]
Please add the Compatibility with the Medic role ([https://github.com/mexikoedi/ttt2_role_med](https://github.com/mexikoedi/ttt2_role_med)). It should not be possible for the Executioner to get the Medic as target since the Medic is neutral and should not be killed.

**Comment by ZacharyHinds** [comment]
Added compatibility, Medic should no longer be able to be targeted by the Executioner
