### ISSUE TITLE
changing Target's when their target joined their team

### ISSUE THREAD

**Issue by PROFI5** [ZacharyHinds/ttt2-role-executioner#15]
assuming theres a amnesiac/beggar or Pirate they would have either to wait until they die. it would be good if target changed when they turned into their team

**Comment by ZacharyHinds** [comment]
I'm fairly certain I already check for this. Can you check if this doesn't already happen when an executioner's target changes team?

**Comment by PROFI5** [comment]
i cant test it but im pretty sure when i was executioner there was an amnesiac turned into a traitor and he was still my target

**Comment by ZacharyHinds** [comment]
I figured out what the issue was and have fixed this. Beggar won't even be able to be a target for the executioner. Even then, any target that joins traitors should be untargeted
